backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "static/images"
public_folder: "/images"
collections:
  - name: "pages"
    label: "Page"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Author", name: "author", widget: "string", default: "Cameron King"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}
